
2021-11-30 14:51:43,215 INFO     [<ipython-input-18-55d77b53df41>:26] Initializing Scraper
2021-11-30 14:52:00,167 ERROR    [<ipython-input-18-55d77b53df41>:61] Message: 
Traceback (most recent call last):
  File "<ipython-input-18-55d77b53df41>", line 54, in __bypass_cookies
    WebDriverWait(self.driver, 10).until(
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-11-30 14:53:39,208 INFO     [<ipython-input-19-55d77b53df41>:26] Initializing Scraper
2021-11-30 14:53:56,496 ERROR    [<ipython-input-19-55d77b53df41>:61] Message: 
Traceback (most recent call last):
  File "<ipython-input-19-55d77b53df41>", line 54, in __bypass_cookies
    WebDriverWait(self.driver, 10).until(
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-11-30 14:54:14,257 INFO     [<ipython-input-20-3ebea962766a>:26] Initializing Scraper
2021-11-30 14:54:14,258 INFO     [<ipython-input-20-3ebea962766a>:26] Initializing Scraper
2021-11-30 14:54:14,259 INFO     [<ipython-input-20-3ebea962766a>:26] Initializing Scraper
2021-11-30 14:54:35,210 ERROR    [<ipython-input-20-3ebea962766a>:61] Message: 
Traceback (most recent call last):
  File "<ipython-input-20-3ebea962766a>", line 54, in __bypass_cookies
    WebDriverWait(self.driver, 10).until(
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-11-30 14:54:36,313 INFO     [<ipython-input-20-3ebea962766a>:70] Depart date changed to 2022-01-10
2021-11-30 14:54:36,313 INFO     [<ipython-input-20-3ebea962766a>:74] Destination changed to NYC
2021-11-30 14:54:36,313 INFO     [<ipython-input-20-3ebea962766a>:77] Return date changed to 2022-01-14
2021-11-30 14:54:37,691 INFO     [<ipython-input-20-3ebea962766a>:70] Depart date changed to 2022-01-10
2021-11-30 14:54:37,692 INFO     [<ipython-input-20-3ebea962766a>:74] Destination changed to ROM
2021-11-30 14:54:37,692 INFO     [<ipython-input-20-3ebea962766a>:77] Return date changed to 2022-01-14
2021-11-30 14:54:38,004 INFO     [<ipython-input-20-3ebea962766a>:70] Depart date changed to 2022-01-10
2021-11-30 14:54:38,004 INFO     [<ipython-input-20-3ebea962766a>:74] Destination changed to RMU
2021-11-30 14:54:38,004 INFO     [<ipython-input-20-3ebea962766a>:77] Return date changed to 2022-01-14
2021-11-30 14:54:40,795 INFO     [<ipython-input-20-3ebea962766a>:106] Getting information on flights
2021-11-30 14:54:43,868 INFO     [<ipython-input-20-3ebea962766a>:106] Getting information on flights
2021-11-30 14:54:45,289 INFO     [<ipython-input-20-3ebea962766a>:106] Getting information on flights
2021-11-30 14:54:49,757 INFO     [<ipython-input-20-3ebea962766a>:26] Initializing Scraper
2021-11-30 14:54:56,091 INFO     [<ipython-input-20-3ebea962766a>:109] No flights available for Murcia
2021-11-30 14:55:04,360 INFO     [<ipython-input-20-3ebea962766a>:70] Depart date changed to 2022-01-10
2021-11-30 14:55:04,360 INFO     [<ipython-input-20-3ebea962766a>:74] Destination changed to TCI
2021-11-30 14:55:04,360 INFO     [<ipython-input-20-3ebea962766a>:77] Return date changed to 2022-01-14
2021-11-30 14:55:09,672 INFO     [<ipython-input-20-3ebea962766a>:106] Getting information on flights
2021-11-30 14:55:54,641 INFO     [<ipython-input-20-3ebea962766a>:26] Initializing Scraper
2021-11-30 14:55:54,642 INFO     [<ipython-input-20-3ebea962766a>:26] Initializing Scraper
2021-11-30 14:56:11,446 INFO     [<ipython-input-20-3ebea962766a>:70] Depart date changed to 2022-01-10
2021-11-30 14:56:11,453 INFO     [<ipython-input-20-3ebea962766a>:74] Destination changed to NYC
2021-11-30 14:56:11,453 INFO     [<ipython-input-20-3ebea962766a>:77] Return date changed to 2022-01-14
2021-11-30 14:56:13,903 INFO     [<ipython-input-20-3ebea962766a>:70] Depart date changed to 2022-01-10
2021-11-30 14:56:13,903 INFO     [<ipython-input-20-3ebea962766a>:74] Destination changed to RMU
2021-11-30 14:56:13,903 INFO     [<ipython-input-20-3ebea962766a>:77] Return date changed to 2022-01-14
2021-11-30 14:56:17,262 INFO     [<ipython-input-20-3ebea962766a>:106] Getting information on flights
2021-11-30 14:56:18,688 INFO     [<ipython-input-20-3ebea962766a>:106] Getting information on flights
2021-11-30 14:56:32,518 INFO     [<ipython-input-20-3ebea962766a>:109] No flights available for Murcia
2021-11-30 14:57:23,817 INFO     [<ipython-input-21-3ebea962766a>:26] Initializing Scraper
2021-11-30 14:57:37,277 INFO     [<ipython-input-21-3ebea962766a>:70] Depart date changed to 2022-01-10
2021-11-30 14:57:37,277 INFO     [<ipython-input-21-3ebea962766a>:74] Destination changed to RMU
2021-11-30 14:57:37,277 INFO     [<ipython-input-21-3ebea962766a>:77] Return date changed to 2022-01-14
2021-11-30 14:57:40,316 INFO     [<ipython-input-21-3ebea962766a>:106] Getting information on flights
2021-11-30 14:57:55,397 INFO     [<ipython-input-21-3ebea962766a>:109] No flights available for Murcia
2021-11-30 14:58:10,942 INFO     [<ipython-input-1-3ebea962766a>:26] Initializing Scraper
2021-11-30 14:58:10,943 INFO     [<ipython-input-1-3ebea962766a>:26] Initializing Scraper
2021-11-30 14:58:24,682 ERROR    [<ipython-input-1-3ebea962766a>:61] Message: 
Traceback (most recent call last):
  File "<ipython-input-1-3ebea962766a>", line 54, in __bypass_cookies
    WebDriverWait(self.driver, 10).until(
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-11-30 14:58:42,391 INFO     [<ipython-input-2-3ebea962766a>:26] Initializing Scraper
2021-11-30 14:58:42,393 INFO     [<ipython-input-2-3ebea962766a>:26] Initializing Scraper
2021-11-30 14:59:00,012 INFO     [<ipython-input-2-3ebea962766a>:70] Depart date changed to 2022-01-10
2021-11-30 14:59:00,013 INFO     [<ipython-input-2-3ebea962766a>:74] Destination changed to RMU
2021-11-30 14:59:00,013 INFO     [<ipython-input-2-3ebea962766a>:77] Return date changed to 2022-01-14
2021-11-30 14:59:03,097 INFO     [<ipython-input-2-3ebea962766a>:106] Getting information on flights
2021-11-30 14:59:18,530 INFO     [<ipython-input-2-3ebea962766a>:109] No flights available for Murcia
2021-11-30 15:01:07,733 INFO     [<ipython-input-1-0e60f3bc661c>:29] Initializing Scraper
2021-11-30 15:01:07,734 INFO     [<ipython-input-1-0e60f3bc661c>:29] Initializing Scraper
2021-11-30 15:01:24,148 INFO     [<ipython-input-1-0e60f3bc661c>:83] Depart date changed to 2022-01-10
2021-11-30 15:01:24,148 INFO     [<ipython-input-1-0e60f3bc661c>:87] Destination changed to BUD
2021-11-30 15:01:24,148 INFO     [<ipython-input-1-0e60f3bc661c>:90] Return date changed to 2022-01-14
2021-11-30 15:01:24,931 INFO     [<ipython-input-1-0e60f3bc661c>:83] Depart date changed to 2022-01-10
2021-11-30 15:01:24,932 INFO     [<ipython-input-1-0e60f3bc661c>:87] Destination changed to RMU
2021-11-30 15:01:24,932 INFO     [<ipython-input-1-0e60f3bc661c>:90] Return date changed to 2022-01-14
2021-11-30 15:01:26,019 INFO     [<ipython-input-1-0e60f3bc661c>:119] Getting information on flights
2021-11-30 15:01:28,241 INFO     [<ipython-input-1-0e60f3bc661c>:119] Getting information on flights
2021-11-30 15:01:43,470 INFO     [<ipython-input-1-0e60f3bc661c>:124] No flights available for Murcia
2021-11-30 15:01:48,551 INFO     [<ipython-input-1-0e60f3bc661c>:29] Initializing Scraper
2021-11-30 15:01:48,557 INFO     [<ipython-input-1-0e60f3bc661c>:29] Initializing Scraper
2021-11-30 15:02:03,012 ERROR    [<ipython-input-1-0e60f3bc661c>:74] Message: 
Traceback (most recent call last):
  File "<ipython-input-1-0e60f3bc661c>", line 67, in __bypass_cookies
    WebDriverWait(self.driver, 10).until(
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-11-30 15:02:03,629 INFO     [<ipython-input-1-0e60f3bc661c>:83] Depart date changed to 2022-01-10
2021-11-30 15:02:03,629 INFO     [<ipython-input-1-0e60f3bc661c>:87] Destination changed to RMU
2021-11-30 15:02:03,629 INFO     [<ipython-input-1-0e60f3bc661c>:90] Return date changed to 2022-01-14
2021-11-30 15:02:05,164 INFO     [<ipython-input-1-0e60f3bc661c>:119] Getting information on flights
2021-11-30 15:02:20,434 INFO     [<ipython-input-1-0e60f3bc661c>:124] No flights available for Murcia
2021-11-30 15:04:37,590 INFO     [<ipython-input-2-9495790bed66>:29] Initializing Scraper
2021-11-30 15:04:56,947 ERROR    [<ipython-input-2-9495790bed66>:74] Message: 
Traceback (most recent call last):
  File "<ipython-input-2-9495790bed66>", line 67, in __bypass_cookies
    WebDriverWait(self.driver, 10).until(
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-11-30 15:06:03,389 INFO     [<ipython-input-3-0e60f3bc661c>:29] Initializing Scraper
2021-11-30 15:06:03,397 INFO     [<ipython-input-3-0e60f3bc661c>:29] Initializing Scraper
2021-11-30 15:06:24,431 ERROR    [<ipython-input-3-0e60f3bc661c>:74] Message: 
Traceback (most recent call last):
  File "<ipython-input-3-0e60f3bc661c>", line 67, in __bypass_cookies
    WebDriverWait(self.driver, 10).until(
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-11-30 15:06:25,488 INFO     [<ipython-input-3-0e60f3bc661c>:83] Depart date changed to 2022-01-10
2021-11-30 15:06:25,488 INFO     [<ipython-input-3-0e60f3bc661c>:87] Destination changed to BUD
2021-11-30 15:06:25,488 INFO     [<ipython-input-3-0e60f3bc661c>:90] Return date changed to 2022-01-14
2021-11-30 15:06:31,561 INFO     [<ipython-input-3-0e60f3bc661c>:119] Getting information on flights
2021-12-01 16:04:12,445 INFO     [<ipython-input-1-a920348bd69b>:29] Initializing Scraper
2021-12-01 16:04:12,446 INFO     [<ipython-input-1-a920348bd69b>:29] Initializing Scraper
2021-12-01 16:04:12,446 INFO     [<ipython-input-1-a920348bd69b>:29] Initializing Scraper
2021-12-01 16:04:33,531 INFO     [<ipython-input-1-a920348bd69b>:83] Depart date changed to 2022-01-10
2021-12-01 16:04:33,533 INFO     [<ipython-input-1-a920348bd69b>:87] Destination changed to AMS
2021-12-01 16:04:33,533 INFO     [<ipython-input-1-a920348bd69b>:90] Return date changed to 2022-01-14
2021-12-01 16:04:33,861 INFO     [<ipython-input-1-a920348bd69b>:83] Depart date changed to 2022-01-10
2021-12-01 16:04:33,861 INFO     [<ipython-input-1-a920348bd69b>:87] Destination changed to ALC
2021-12-01 16:04:33,861 INFO     [<ipython-input-1-a920348bd69b>:90] Return date changed to 2022-01-14
2021-12-01 16:04:36,340 INFO     [<ipython-input-1-a920348bd69b>:119] Getting information on flights
2021-12-01 16:04:37,176 INFO     [<ipython-input-1-a920348bd69b>:119] Getting information on flights
2021-12-01 16:04:38,339 INFO     [<ipython-input-1-a920348bd69b>:83] Depart date changed to 2022-01-10
2021-12-01 16:04:38,340 INFO     [<ipython-input-1-a920348bd69b>:87] Destination changed to DPS
2021-12-01 16:04:38,340 INFO     [<ipython-input-1-a920348bd69b>:90] Return date changed to 2022-01-14
2021-12-01 16:04:41,268 INFO     [<ipython-input-1-a920348bd69b>:119] Getting information on flights
2021-12-01 16:04:47,617 INFO     [<ipython-input-1-a920348bd69b>:29] Initializing Scraper
2021-12-01 16:04:48,477 INFO     [<ipython-input-1-a920348bd69b>:29] Initializing Scraper
2021-12-01 16:04:53,044 INFO     [<ipython-input-1-a920348bd69b>:29] Initializing Scraper
2021-12-01 16:04:57,972 ERROR    [<ipython-input-1-a920348bd69b>:74] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback (most recent call last):
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/http/client.py", line 288, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<ipython-input-1-a920348bd69b>", line 67, in __bypass_cookies
    WebDriverWait(self.driver, 10).until(
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 64, in __call__
    return _find_element(driver, self.locator)
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/http/client.py", line 288, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-01 16:04:57,996 INFO     [<ipython-input-1-a920348bd69b>:29] Initializing Scraper
2021-12-01 16:04:58,011 INFO     [<ipython-input-1-a920348bd69b>:29] Initializing Scraper
2021-12-01 16:04:58,032 WARNING  [connectionpool.py:780] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8090449d90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d8284256b1da57524478a1f6f97a7c24/element
2021-12-01 16:04:58,037 WARNING  [connectionpool.py:780] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8070ed67c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d8284256b1da57524478a1f6f97a7c24/element
2021-12-01 16:04:58,042 WARNING  [connectionpool.py:780] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8070ed6460>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d8284256b1da57524478a1f6f97a7c24/element
2021-12-01 16:04:58,046 INFO     [<ipython-input-1-a920348bd69b>:29] Initializing Scraper
2021-12-01 16:05:17,593 ERROR    [<ipython-input-1-a920348bd69b>:74] Message: 
Traceback (most recent call last):
  File "<ipython-input-1-a920348bd69b>", line 67, in __bypass_cookies
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-12-01 16:05:17,633 INFO     [<ipython-input-1-a920348bd69b>:29] Initializing Scraper
2021-12-01 16:05:24,455 INFO     [<ipython-input-1-a920348bd69b>:83] Depart date changed to 2022-01-10
2021-12-01 16:05:24,456 INFO     [<ipython-input-1-a920348bd69b>:87] Destination changed to BUD
2021-12-01 16:05:24,456 INFO     [<ipython-input-1-a920348bd69b>:90] Return date changed to 2022-01-14
2021-12-01 16:05:26,602 INFO     [<ipython-input-1-a920348bd69b>:83] Depart date changed to 2022-01-10
2021-12-01 16:05:26,602 INFO     [<ipython-input-1-a920348bd69b>:87] Destination changed to ALC
2021-12-01 16:05:26,602 INFO     [<ipython-input-1-a920348bd69b>:90] Return date changed to 2022-01-14
2021-12-01 16:05:28,079 INFO     [<ipython-input-1-a920348bd69b>:119] Getting information on flights
2021-12-01 16:05:30,337 INFO     [<ipython-input-1-a920348bd69b>:29] Initializing Scraper
2021-12-01 16:05:30,340 INFO     [<ipython-input-1-a920348bd69b>:29] Initializing Scraper
2021-12-01 16:05:30,873 ERROR    [<ipython-input-1-a920348bd69b>:74] Message: chrome not reachable
  (Session info: headless chrome=96.0.4664.55)
Traceback (most recent call last):
  File "<ipython-input-1-a920348bd69b>", line 67, in __bypass_cookies
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 64, in __call__
    return _find_element(driver, self.locator)
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 415, in _find_element
    raise e
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=96.0.4664.55)

2021-12-01 16:05:30,876 INFO     [<ipython-input-1-a920348bd69b>:29] Initializing Scraper
2021-12-01 16:05:47,126 INFO     [<ipython-input-1-57b91029368b>:29] Initializing Scraper
2021-12-01 16:05:47,128 INFO     [<ipython-input-1-57b91029368b>:29] Initializing Scraper
2021-12-01 16:06:11,228 ERROR    [<ipython-input-1-57b91029368b>:74] Message: 
Traceback (most recent call last):
  File "<ipython-input-1-57b91029368b>", line 67, in __bypass_cookies
    WebDriverWait(self.driver, 10).until(
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-12-01 16:06:11,372 ERROR    [<ipython-input-1-57b91029368b>:74] Message: 
Traceback (most recent call last):
  File "<ipython-input-1-57b91029368b>", line 67, in __bypass_cookies
    WebDriverWait(self.driver, 10).until(
  File "/Users/dan/opt/miniconda3/envs/AICore/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-12-01 16:06:12,853 INFO     [<ipython-input-1-57b91029368b>:83] Depart date changed to 2022-01-10
2021-12-01 16:06:12,856 INFO     [<ipython-input-1-57b91029368b>:87] Destination changed to RMU
2021-12-01 16:06:12,856 INFO     [<ipython-input-1-57b91029368b>:90] Return date changed to 2022-01-14
2021-12-01 16:06:16,601 INFO     [<ipython-input-1-57b91029368b>:119] Getting information on flights
2021-12-01 16:06:31,883 INFO     [<ipython-input-1-57b91029368b>:124] No flights available for Murcia
2021-12-01 16:07:40,503 INFO     [<ipython-input-1-2e4bfbdb133b>:29] Initializing Scraper
2021-12-01 16:07:56,335 INFO     [<ipython-input-1-2e4bfbdb133b>:83] Depart date changed to 2022-01-10
2021-12-01 16:07:56,336 INFO     [<ipython-input-1-2e4bfbdb133b>:87] Destination changed to FAO
2021-12-01 16:07:56,336 INFO     [<ipython-input-1-2e4bfbdb133b>:90] Return date changed to 2022-01-14
2021-12-01 16:07:58,891 INFO     [<ipython-input-1-2e4bfbdb133b>:119] Getting information on flights
2021-12-01 16:08:35,869 INFO     [<ipython-input-1-194307553567>:29] Initializing Scraper
2021-12-01 16:08:35,870 INFO     [<ipython-input-1-194307553567>:29] Initializing Scraper
2021-12-01 16:08:52,058 INFO     [<ipython-input-1-194307553567>:83] Depart date changed to 2022-01-10
2021-12-01 16:08:52,058 INFO     [<ipython-input-1-194307553567>:87] Destination changed to FAO
2021-12-01 16:08:52,058 INFO     [<ipython-input-1-194307553567>:90] Return date changed to 2022-01-14
2021-12-01 16:08:53,322 INFO     [<ipython-input-1-194307553567>:83] Depart date changed to 2022-01-10
2021-12-01 16:08:53,322 INFO     [<ipython-input-1-194307553567>:87] Destination changed to RMU
2021-12-01 16:08:53,322 INFO     [<ipython-input-1-194307553567>:90] Return date changed to 2022-01-14
2021-12-01 16:08:55,312 INFO     [<ipython-input-1-194307553567>:119] Getting information on flights
2021-12-01 16:08:56,263 INFO     [<ipython-input-1-194307553567>:119] Getting information on flights
2021-12-01 16:09:10,406 INFO     [<ipython-input-1-194307553567>:124] No flights available for Murcia
